### ISSUE TITLE
Stable rust

### ISSUE THREAD

**Issue by explosion-mental** [seijikun/kmean-rs#5]
`packet_simd` only works on stable (and I think `portable_simd` is it's replacement), so while [that stabilizes](https://github.com/rust-lang/rfcs/pull/2366] I propose having a feature flag for stable rust, either by using another crate or disabling simd all together.

**Comment by seijikun** [comment]
`kmeans` was created with SIMD as a design decision to the core, because everything else I tried at the time (including Matlab, a nalgebra implementation, ...) was too slow.
Making it build with stable would mean implementing **everything** a second time and maintaining it alongside.
Since I'm not using the library myself anymore, I'm afraid that's not in-scope for me. Sorry.
I admit that the naming `kmeans` might have been rather unfortunate (since too generic).

**Comment by explosion-mental** [comment]
I understand, thanks for the work being done.

**Comment by cyypherus** [comment]
If nothing else, it may be useful to document the requirement for unstable rust 🙂
